version: '3'
services:
  db: 
    image: mysql
    container_name: test_db
    ports: 
      - "3600:3600"
    volumes:
      - /home/user/data/mysql_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: webapp
      MYSQL_ROOT_PASSWORD: 7895123_new
  
  apcherphp:
    build: .
    container_name: web_test
    ports:
      - "80:80"
    volumes:
      - /home/user/data/webapp:/var/www/html
    depends_on:
      - db