---
- name: mysql db_prepare
  hosts: all
  become: yes

  tasks:
    - name: create user sysdba
      mysql_user:
        name: sysdba
        host: '%'
        password: 123456
        priv: '*.*:ALL'
        state: present

    - name: create db web_app
      mysql_db:
        name: webapp
        state: present

    - name: webapp dump_restore
      mysql_db:
        state: import
        name: webapp
        target: /home/vagrant/web_app/webapp.sql